# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  setup:
    cmds:
      - docker compose run --rm --workdir=/zmk zmk west update

  cli:
    cmds:
      - docker compose run --rm --workdir=/zmk zmk bash

  build:
    cmds:
      - docker compose run --rm --workdir=/zmk zmk bash -c ./build.sh
