name: "zmk"

services:
  zmk:
    image: zmkfirmware/zmk-build-arm:stable
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # command: ["/scripts/run-api.sh", "--port", "8000", "--reload"]
    # env_file:
    #   - ./src/.env
    # ports:
    #   - "8000:8000"
    # depends_on:
    #   - db
    #   - redis
    volumes:
      - ./zmk-clavis:/zmk
    #  - ./build:/build
      - ./firmware:/firmware
    #   - ./tests:/code/tests
    #   - ./scripts:/scripts
    #   - ./assets:/assets
    environment:
      - CMAKE_PREFIX_PATH=/zmk/zephyr

